@baseurl = http://localhost:3000


POST {{baseurl}}/signup
Content-Type: application/json

{
    "email" : "SKy78@gmail.com",
    "password" : "neverEverlestThan6"
}

###
POST {{baseurl}}/login
Content-Type: application/json

{
    "email" : "login@gmail.com",
    "password" : "lilyofDeath"
}